// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SiriusTech.Data.Models
{
    public partial class Cliente
    {
        public Cliente()
        {
            ProdutoCliente = new HashSet<ProdutoCliente>();
        }

        [Key]
        [Column("id")]
        public int Id { get; set; }
        [Column("cpf_cnpj")]
        [StringLength(100)]
        [DisplayName("Cpf_Cnpj")]
        [Unicode(false)]
        public string CpfCnpj { get; set; }
        [Column("nome")]
        [StringLength(50)]
        [DisplayName("Nome do Cliente")]
        [Unicode(false)]
        public string Nome { get; set; }
        [Column("endereco")]
        [StringLength(50)]
        [Unicode(false)]
        public string Endereco { get; set; }
        [Column("cidade")]
        [StringLength(50)]
        [Unicode(false)]
        public string Cidade { get; set; }
        [Column("bairro")]
        [StringLength(50)]
        [Unicode(false)]
        public string Bairro { get; set; }

        [InverseProperty("IdClienteNavigation")]
        public virtual ICollection<ProdutoCliente> ProdutoCliente { get; set; }
    }
}