// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SiriusTech.Data.Models
{
    public partial class Entidade
    {
        public Entidade()
        {
            Movimentacao = new HashSet<Movimentacao>();
        }

        [Key]
        [Column("idEntidade")]
        public int IdEntidade { get; set; }
        [Column("dataRegistro", TypeName = "datetime")]
        public DateTime? DataRegistro { get; set; }
        [Column("cpf_cnpj")]
        [StringLength(100)]
        public string CpfCnpj { get; set; }
        [Column("dcrEntidade")]
        [StringLength(50)]
        public string DcrEntidade { get; set; }
        [Column("dcrCep")]
        [StringLength(50)]
        public string DcrCep { get; set; }
        [Column("dcrEndereco")]
        [StringLength(50)]
        public string DcrEndereco { get; set; }
        [Column("dcrNumero")]
        [StringLength(50)]
        public string DcrNumero { get; set; }
        [Column("idCidade")]
        public int? IdCidade { get; set; }
        [Column("idBairro")]
        public int? IdBairro { get; set; }
        [Column("idEstado")]
        public int? IdEstado { get; set; }
        [Column("idPais")]
        public int? IdPais { get; set; }
        [Column("idTipoEntidade")]
        public int? IdTipoEntidade { get; set; }

        [ForeignKey("IdTipoEntidade")]
        [InverseProperty("Entidade")]
        public virtual TipoEntidade IdTipoEntidadeNavigation { get; set; }
        [InverseProperty("IdEntidadeNavigation")]
        public virtual ICollection<Movimentacao> Movimentacao { get; set; }
    }
}