// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SiriusTech.Data.Models
{
    public partial class MovimentacaoItem
    {
        [Key]
        [Column("idMovimentacaoItem")]
        public int IdMovimentacaoItem { get; set; }
        [Column("dataRegistro", TypeName = "datetime")]
        public DateTime? DataRegistro { get; set; }
        [Column("dcrMovimentacaoItem")]
        [StringLength(50)]
        public string DcrMovimentacaoItem { get; set; }
        [Column("idMovimentacao")]
        public int? IdMovimentacao { get; set; }
        [Column("idProduto")]
        public int? IdProduto { get; set; }
        [Column("idPedido")]
        public int? IdPedido { get; set; }
        [Column("idCotacao")]
        public int? IdCotacao { get; set; }
        [Column("idOrdem")]
        public int? IdOrdem { get; set; }

        [ForeignKey("IdCotacao")]
        [InverseProperty("MovimentacaoItem")]
        public virtual Cotacao IdCotacaoNavigation { get; set; }
        [ForeignKey("IdMovimentacao")]
        [InverseProperty("MovimentacaoItem")]
        public virtual Movimentacao IdMovimentacaoNavigation { get; set; }
        [ForeignKey("IdOrdem")]
        [InverseProperty("MovimentacaoItem")]
        public virtual Ordem IdOrdemNavigation { get; set; }
        [ForeignKey("IdPedido")]
        [InverseProperty("MovimentacaoItem")]
        public virtual Pedido IdPedidoNavigation { get; set; }
        [ForeignKey("IdProduto")]
        [InverseProperty("MovimentacaoItem")]
        public virtual Produto IdProdutoNavigation { get; set; }
    }
}