// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SiriusTech.Data.Models
{
    public partial class Movimentacao
    {
        public Movimentacao()
        {
            Boleto = new HashSet<Boleto>();
            MovimentacaoItem = new HashSet<MovimentacaoItem>();
        }

        [Key]
        [Column("idMovimentacao")]
        public int IdMovimentacao { get; set; }
        [Column("dataRegistro", TypeName = "datetime")]
        public DateTime? DataRegistro { get; set; }
        [Column("dcrMovimentacao")]
        [StringLength(50)]
        public string DcrMovimentacao { get; set; }
        [Column("idTipoMovimentacao")]
        public int? IdTipoMovimentacao { get; set; }
        [Column("idEntidade")]
        public int? IdEntidade { get; set; }

        [ForeignKey("IdEntidade")]
        [InverseProperty("Movimentacao")]
        public virtual Entidade IdEntidadeNavigation { get; set; }
        [ForeignKey("IdTipoMovimentacao")]
        [InverseProperty("Movimentacao")]
        public virtual TipoMovimentacao IdTipoMovimentacaoNavigation { get; set; }
        [InverseProperty("IdMovimentacaoNavigation")]
        public virtual ICollection<Boleto> Boleto { get; set; }
        [InverseProperty("IdMovimentacaoNavigation")]
        public virtual ICollection<MovimentacaoItem> MovimentacaoItem { get; set; }
    }
}