// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SiriusTech.Data.Models
{
    public partial class Ordem
    {
        public Ordem()
        {
            MovimentacaoItem = new HashSet<MovimentacaoItem>();
        }

        [Key]
        [Column("idOrdem")]
        public int IdOrdem { get; set; }
        [Column("dataRegistro", TypeName = "datetime")]
        public DateTime? DataRegistro { get; set; }
        [Column("dcrOrdem")]
        [StringLength(50)]
        public string DcrOrdem { get; set; }
        [Column("idTipoOrdem")]
        public int? IdTipoOrdem { get; set; }

        [ForeignKey("IdTipoOrdem")]
        [InverseProperty("Ordem")]
        public virtual TipoOrdem IdTipoOrdemNavigation { get; set; }
        [InverseProperty("IdOrdemNavigation")]
        public virtual ICollection<MovimentacaoItem> MovimentacaoItem { get; set; }
    }
}