// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SiriusTech.Data.Models
{
    public partial class Pedido
    {
        public Pedido()
        {
            MovimentacaoItem = new HashSet<MovimentacaoItem>();
        }

        [Key]
        [Column("idPedido")]
        public int IdPedido { get; set; }
        [Column("dataRegistro", TypeName = "datetime")]
        public DateTime? DataRegistro { get; set; }
        [Column("dcrPedido")]
        [StringLength(50)]
        public string DcrPedido { get; set; }

        [InverseProperty("IdPedidoNavigation")]
        public virtual ICollection<MovimentacaoItem> MovimentacaoItem { get; set; }
    }
}