// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SiriusTech.Data.Models
{
    public partial class Produto
    {
        public Produto()
        {
            ProdutoCliente = new HashSet<ProdutoCliente>();
        }

        [Key]
        [Column("id")]
        public int Id { get; set; }
        [Column("nome")]
        [StringLength(50)]
        [DisplayName("Nome do Produto")]
        [Unicode(false)]
        public string Nome { get; set; }

        [InverseProperty("IdProdutoNavigation")]
        public virtual ICollection<ProdutoCliente> ProdutoCliente { get; set; }
    }
}