// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;

namespace SiriusTech.Data.Models
{
    public partial class SiriusTechContext : DbContext
    {
        public SiriusTechContext()
        {
        }

        public SiriusTechContext(DbContextOptions<SiriusTechContext> options)
            : base(options)
        {
        }

        public virtual DbSet<Cliente> Cliente { get; set; }
        public virtual DbSet<Produto> Produto { get; set; }
        public virtual DbSet<ProdutoCliente> ProdutoCliente { get; set; }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            if (!optionsBuilder.IsConfigured)
            {
//#warning To protect potentially sensitive information in your connection string, you should move it out of source code. You can avoid scaffolding the connection string by using the Name= syntax to read it from configuration - see https://go.microsoft.com/fwlink/?linkid=2131148. For more guidance on storing connection strings, see http://go.microsoft.com/fwlink/?LinkId=723263.
                optionsBuilder.UseSqlServer("Data Source=DESKTOP-2RIAP0H\\MSSQLSIRIUS;Initial Catalog=SiriusTech;Persist Security Info=True;User ID=sa;Password=h1Y2n3F4;encrypt=yes;trustservercertificate=true;");
            }
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<ProdutoCliente>(entity =>
            {
                entity.HasOne(d => d.IdClienteNavigation)
                    .WithMany(p => p.ProdutoCliente)
                    .HasForeignKey(d => d.IdCliente)
                    .HasConstraintName("FK_Produto_Cliente_Cliente");

                entity.HasOne(d => d.IdProdutoNavigation)
                    .WithMany(p => p.ProdutoCliente)
                    .HasForeignKey(d => d.IdProduto)
                    .HasConstraintName("FK_Produto_Cliente_Produto");
            });

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}