// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SiriusTech.Data.Models
{
    public partial class TipoEntidade
    {
        public TipoEntidade()
        {
            Entidade = new HashSet<Entidade>();
        }

        [Key]
        [Column("idTipoEntidade")]
        public int IdTipoEntidade { get; set; }
        [Column("dataRegistro", TypeName = "datetime")]
        public DateTime? DataRegistro { get; set; }
        [Column("dcrTipoEntidade")]
        [StringLength(50)]
        public string DcrTipoEntidade { get; set; }

        [InverseProperty("IdTipoEntidadeNavigation")]
        public virtual ICollection<Entidade> Entidade { get; set; }
    }
}