// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SiriusTech.Data.Models
{
    public partial class TipoMovimentacao
    {
        public TipoMovimentacao()
        {
            Movimentacao = new HashSet<Movimentacao>();
        }

        [Key]
        [Column("idTipoMovimentacao")]
        public int IdTipoMovimentacao { get; set; }
        [Column("dataRegistro", TypeName = "datetime")]
        public DateTime? DataRegistro { get; set; }
        [Column("dcrTipoMovimentacao")]
        [StringLength(50)]
        public string DcrTipoMovimentacao { get; set; }

        [InverseProperty("IdTipoMovimentacaoNavigation")]
        public virtual ICollection<Movimentacao> Movimentacao { get; set; }
    }
}