// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SiriusTech.Data.Models
{
    public partial class TipoOrdem
    {
        public TipoOrdem()
        {
            Ordem = new HashSet<Ordem>();
        }

        [Key]
        [Column("idTipoOrdem")]
        public int IdTipoOrdem { get; set; }
        [Column("dataRegistro", TypeName = "datetime")]
        public DateTime? DataRegistro { get; set; }
        [Column("dcrTipoOrdem")]
        [StringLength(50)]
        public string DcrTipoOrdem { get; set; }

        [InverseProperty("IdTipoOrdemNavigation")]
        public virtual ICollection<Ordem> Ordem { get; set; }
    }
}