// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SiriusTech.Data.Models
{
    public partial class Usuario
    {
        [Key]
        [Column("idUsuario")]
        public int IdUsuario { get; set; }
        [Column("dataRegistro", TypeName = "datetime")]
        public DateTime? DataRegistro { get; set; }
        [Column("dcrUsuario")]
        [StringLength(50)]
        public string DcrUsuario { get; set; }
        [Column("dcrNome")]
        [StringLength(50)]
        public string DcrNome { get; set; }
        [Column("dcrSenha")]
        [StringLength(50)]
        public string DcrSenha { get; set; }
    }
}