// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SiriusTech.Data.Models
{
    //[Keyless]
    public partial class ViewMovimentacao
    {
        [Column("dcrTipoMovimentacao")]
        [StringLength(50)]
        public string DcrTipoMovimentacao { get; set; }
        [Column("dcrEntidade")]
        [StringLength(50)]
        public string DcrEntidade { get; set; }
        [Column("idMovimentacao")]
        public int IdMovimentacao { get; set; }
        [Column("dataRegistro", TypeName = "datetime")]
        public DateTime? DataRegistro { get; set; }
        [Column("dcrMovimentacao")]
        [StringLength(50)]
        public string DcrMovimentacao { get; set; }
        [Column("idTipoMovimentacao")]
        public int? IdTipoMovimentacao { get; set; }
        [Column("idEntidade")]
        public int? IdEntidade { get; set; }
    }
}